building_addresses = [
    '161 E 1',
    '311 E 6',
    '555 Abbott', 
    '183 Keefer',
    '618 Abbott',
    '688 Abbott',
    '58 Keefer',
    '633 Abbott',
    '689 Abbott',
    '188 Keefer',
    '907 Beach',
    '1003 Burnaby',
    '1050 Burrard',
    '1160 Burrard',
    '1238 Burrard',
    '370 Carrall',
    '1010 Chilco',
    '55 E Cordova',
    '1249 Granville',
    '933 E Hastings', 
    '955 E Hastings', 
    '983 E Hastings',
    '1228 Homer',
    '1010 Howe',
    '718 Main',
    '1166 Melville',
    '989 Nelson',
    '28 Powell',
    '933 Seymour',
    '1372 Seymour',
    '919 Station',
    '928 Richards',
    '231 E Pender',
    '33 W Pender',
]

building_names = [
    'Block 100',
    'The Wohlsein',
    'Paris Place',
    'Firenze',
    'Espana',
    'Coral Court',
    'The Milano',
    'The Wall Centre',
    'Burrard Health',
    'Altadena',
    '21 Doors',
    'Chilco Park',
    'Koret Lofts',
    'The Lex',
    'Strathcona Village',
    'Ellison',
    'Fortune House',
    'Ginger',
    'Orca Place',
    'Electra',
    'Powell Lane',
    'The Spot',
    'The Mark',
    'The Left Bank',
    'The Savoy',
    'Framework',
    '33 Living',
]
